
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanDoTrangMieng
{

using System;
    using System.Collections.Generic;
    
public partial class Payment
{

    public int PaymentId { get; set; }

    public int OrderId { get; set; }

    public int PaymentMethodId { get; set; }

    public decimal Amount { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Status { get; set; }



    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

}

}
