//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTrangMieng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
            this.Reviews = new HashSet<Review>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Order_Product> Order_Product { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
